#!/usr/bin/env python3
"""Emit a hollow box room as a Valve 220 .map. Brushes are winding-agnostic (the engine orients
normals outward), so each face is just 3 points on its plane. Run: python tools/gen_room.py > maps/room.map"""

# Per-face Valve texture axes chosen so UVs read sensibly on each orientation.
AXES = {
    "x": ("[ 0 1 0 0 ]", "[ 0 0 -1 0 ]"),   # +/-X faces: U=Y, V=Z
    "y": ("[ 1 0 0 0 ]", "[ 0 0 -1 0 ]"),   # +/-Y faces: U=X, V=Z
    "z": ("[ 1 0 0 0 ]", "[ 0 1 0 0 ]"),    # +/-Z faces: U=X, V=Y
}


def face(p1, p2, p3, tex, axis):
    u, v = AXES[axis]
    pts = " ".join(f"( {x} {y} {z} )" for (x, y, z) in (p1, p2, p3))
    return f"{pts} {tex} {u} {v} 0 1 1"


def box(x1, x2, y1, y2, z1, z2, tex):
    f = [
        face((x1, y1, z1), (x1, y2, z1), (x1, y1, z2), tex, "x"),  # -X
        face((x2, y1, z1), (x2, y1, z2), (x2, y2, z1), tex, "x"),  # +X
        face((x1, y1, z1), (x1, y1, z2), (x2, y1, z1), tex, "y"),  # -Y
        face((x1, y2, z1), (x2, y2, z1), (x1, y2, z2), tex, "y"),  # +Y
        face((x1, y1, z1), (x2, y1, z1), (x1, y2, z1), tex, "z"),  # -Z
        face((x1, y1, z2), (x1, y2, z2), (x2, y1, z2), tex, "z"),  # +Z
    ]
    return "{\n" + "\n".join(f) + "\n}"


def room(ix, iy, iz, t, floor_tex, wall_tex):
    hx, hy = ix // 2, iy // 2
    brushes = [
        box(-hx - t, hx + t, -hy - t, hy + t, -t, 0, floor_tex),      # floor
        box(-hx - t, hx + t, -hy - t, hy + t, iz, iz + t, wall_tex),  # ceiling
        box(-hx - t, -hx, -hy - t, hy + t, 0, iz, wall_tex),          # -X wall
        box(hx, hx + t, -hy - t, hy + t, 0, iz, wall_tex),            # +X wall
        box(-hx, hx, -hy - t, -hy, 0, iz, wall_tex),                  # -Y wall
        box(-hx, hx, hy, hy + t, 0, iz, wall_tex),                    # +Y wall
    ]
    out = ["// Game: Adventure", "// Format: Valve",
           "// Generated by tools/gen_room.py - hollow box room.",
           "{", '"classname" "worldspawn"']
    out += brushes
    out += ["}",
            "{", '"classname" "info_player_start"',
            '"origin" "0 0 48"', '"angle" "90"', "}"]
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    print(room(384, 384, 192, 16, "floor_tile_01", "stone_wall_01"), end="")
