#!/usr/bin/env python3
"""Emit a training-ground .map (Valve 220) for measuring movement: a floor, a jump-height staircase,
and a row of crouch bars at decreasing clearance. Jump distance/height are read live from the in-game
telemetry (F4). Run: python tools/gen_training.py > maps/training.map"""

MAP_U = 32.0  # map units per engine unit

AXES = {
    "x": ("[ 0 1 0 0 ]", "[ 0 0 -1 0 ]"),
    "y": ("[ 1 0 0 0 ]", "[ 0 0 -1 0 ]"),
    "z": ("[ 1 0 0 0 ]", "[ 0 1 0 0 ]"),
}


def face(p1, p2, p3, tex, axis):
    u, v = AXES[axis]
    pts = " ".join("( %g %g %g )" % p for p in (p1, p2, p3))
    return "%s %s %s %s 0 1 1" % (pts, tex, u, v)


def box(x1, x2, y1, y2, z1, z2, tex):
    f = [
        face((x1, y1, z1), (x1, y2, z1), (x1, y1, z2), tex, "x"),
        face((x2, y1, z1), (x2, y1, z2), (x2, y2, z1), tex, "x"),
        face((x1, y1, z1), (x1, y1, z2), (x2, y1, z1), tex, "y"),
        face((x1, y2, z1), (x2, y2, z1), (x1, y2, z2), tex, "y"),
        face((x1, y1, z1), (x2, y1, z1), (x1, y2, z1), tex, "z"),
        face((x1, y1, z2), (x1, y2, z2), (x2, y1, z2), tex, "z"),
    ]
    return "{\n" + "\n".join(f) + "\n}"


def e(u):  # engine units -> map units
    return u * MAP_U


brushes = []

# Big floor, top at engine y=0.
brushes.append(box(e(-14), e(14), e(-14), e(14), e(-0.5), 0, "floor_tile_01"))

# Walkable staircase along +X: 6 connected steps rising 0.3 each (<= stepHeight 0.5, walk up, no jump).
for i in range(6):
    top = e(0.3 * (i + 1))
    x0 = e(2) + i * e(1.5)
    brushes.append(box(x0, x0 + e(1.5), e(-2.5), e(2.5), e(-0.5), top, "stone_wall_01"))

# Jump-onto pillars (test jump height ~1.1): tops at 0.6, 1.0, 1.4 engine, in the +X/+Y corner.
for i, top in enumerate((0.6, 1.0, 1.4)):
    x0 = e(3 + i * 2.5)
    brushes.append(box(x0, x0 + e(1.2), e(5), e(6.2), e(-0.5), e(top), "stone_wall_01"))

# Crouch bars along -X: overhead bars with bottoms at decreasing clearance (engine).
for i, clear in enumerate((1.9, 1.6, 1.3, 1.0)):
    x0 = e(-(3 + i * 2.5))
    brushes.append(box(x0, x0 + e(0.6), e(-2.5), e(2.5), e(clear), e(clear + 0.6), "stone_wall_01"))

out = ["// Game: Adventure", "// Format: Valve",
       "// Generated by tools/gen_training.py - movement training ground.",
       "// +X: jump-height staircase (0.5..3.0). -X: crouch bars (clearance 1.9,1.6,1.3,1.0).",
       "// Jump distance/height read live from the in-game telemetry (F4).",
       "{", '"classname" "worldspawn"']
out += brushes
out += ["}", "{", '"classname" "info_player_start"', '"origin" "0 0 48"', '"angle" "90"', "}"]
print("\n".join(out))
